### ISSUE TITLE
New Project Idea

### ISSUE THREAD

**Issue by beeing** [blm768/pg-libphonenumber#8]
Hi @blm768, just wondering are you available to work on a new postgresql extension?

If yes, do provide me your email address. Thanks.

**Comment by blm768** [comment]
I've been relatively busy recently (which is part of the reason that development on `pg-libphonenumber` has been slow), but if the idea seems sufficiently useful and compelling, I might be able to spare some time (although I can't make any guarantees about that). I've just added my email address to my [profile page](https://github.com/blm768), so you should be able to contact me there.

I'll mark this issue as closed for the sake of housekeeping (since it doesn't involve anything actionable with the `pg-libphonenumber` codebase itself), but feel free to continue the conversation via email.
